### ISSUE TITLE
Telemetry.lhs isn't haskell

### ISSUE THREAD

**Issue by cloudhead** [oscoin/oscoin#489]
The `./docs/telemtry.lhs` causes warnings when running `hlint .`, since it isn't actually haskell. Changing the extension to `.md` would make sense, but not sure what the original intent was. /cc @adinapoli-mndc

**Comment by kim** [comment]
@cloudhead https://github.com/sol/markdown-unlit

`hlint .` produces _a lot_ of warnings on a worktree, as it also descends into `dist-newstyle`, `.stack-work`, etc. Since the yaml config doesn't allow excluding any paths, it's probably best to wrap `hlint` in a shell script under `scripts`, which only looks at the interesting parts of the tree.

**Comment by cloudhead** [comment]
Ah right, .lhs is a symlink to the .md ... :thinking: 
I only get *these* warnings when I run `hlint .`, nothing from inside .stack-work etc.

**Comment by adinapoli-mndc** [comment]
Yup, as Kim pointed out the `lhs -> md` tricker is necessary for the `markdown-unlit` pre-processor. I would recommend to simply call `hlint src test` and live and prosper with it 😁 : I had to do exactly that a while ago after I started using `cabal new-build` and, as Kim pointed out, alas `hlint` picks up `dist-newstyle` as a target and spits out a _lot_ of warnings, le sigh.
