### ISSUE TITLE
OscoinTx support for SQLite BlockStore

### ISSUE THREAD

**Issue by cloudhead** [oscoin/oscoin#590]
The current SQLite backend doesn't support OscoinTx. We should implement `FromRow` and `ToRow` instances for `OscoinTx`, as well as a `Serialise` instance.

The integration plan could be as follows:
1. Switch `node/Main.hs` to use the **in-memory** blockstore with the **old** (current) `Tx` type.
2. Merge the new SQLite (OscoinTx) backend.
3. Once things are running fine, switch `Node` over completely from `Tx` to `OscoinTx`, and move back to the SQLite blockstore.

@kim : does this create any complications in terms of the deployment? Specifically if `blockstore.db` is missing, and/or when switching from memory to sqlite?

**Comment by kim** [comment]
I am not sure about the benefits of using the in-memory blockstore, vs. just writing to two tables for a while. Since there are no transactions, I also don't see a problem with just migrating the schema.

That being said, SQLite creates the `blockstore.db` if it doesn't exist, all we do during deployment is mount a directory on an ephemeral SSD into the container.

**Comment by cloudhead** [comment]
Closed by #607
