### ISSUE TITLE
Remove remaining JSON instances

### ISSUE THREAD

**Issue by geigerzaehler** [oscoin/oscoin#602]
### Problem

The code requires a plethora of ToJSON and FromJSON instances to accomplish just one thing: Generate and read the gensis block from a YAML file. To alleviate the burden of maintaing these instances and implementing them for OscoinTx I propose to eliminate them.

### Proposed solutions

We have two solutions to this problem.

#### Storing the genesis block as CBOR

Instead of using YAML to store the genesis block we use the CBOR and the existing Serialise instances.

#### Store only data required to construct Genesis block

We store only the data that is required to construct the genesis block. I.e. the state hash, the timestamp, the beneficiary, the initial difficulty and the pow seal. All other data, like parent hash, data hash, height, etc can be derived from that.

We could then implement some dedicated `genesisFromJson` and `genesisParamsToJson` functions that would not require the ToJSON and FromJSON instances and would be rather minimal.

### Recommendation

I suggest going with the second solution. Decoupling the definition of the genesis block from the serialization of the genesis block will give us more flexibility down the road. For example we could extend the parameters to not include the state hash but an actual definition of the seed state.

**Comment by geigerzaehler** [comment]
Comments @cloudhead, @kim, @adinapoli-mndc?

**Comment by cloudhead** [comment]
Agree with everything said!

**Comment by adinapoli-mndc** [comment]
I like the second solution -- I wouldn't recommend the first (proposed) one simply because having an inspectable and audit-able genesis block is a very valuable property to have, and in the past I did find myself in a situation where this property was not enforced and that lead to pain and frustration (not to mention that _eventually_ genesis went back to be a JSON file 😉 ).

On the topic: any particular reason why not to go with `json` directly for the on-file representation or you guys feel attached to Yaml for any particular reason?
